#!/bin/sh

set -e

/usr/bin/apt-get -qy update > /dev/null
/usr/bin/apt-get -qy upgrade > /dev/null
/usr/bin/apt-get -qy dist-upgrade > /dev/null
/usr/bin/apt-get -qy autoremove > /dev/null
/usr/bin/apt-get -qy autoclean > /dev/null

exit 0
